baseURL = "https://blog.justusweigmann.de"
languageCode = "en-us"
theme = "simple"
themesDir = "themes"
title = "Blog by Justus Weigmann"
paginate = 3
DefaultContentLanguage = "en"
enableInlineShortcodes = true
footnoteReturnLinkContents = "^"

[menu]

  [[menu.main]]
    identifier = "legal"
    name = "LEGAL NOTICE"
    url = "https://justben.de/legal-notice"
    weight = 10

  [[menu.main]]
    identifier = "privacy"
    name = "PRIVACY POLICY"
    url = "https://justben.de/privacy"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"

[params]
description = "Come along with me on my journey as an Information and Communication Technology engineer as I uncover the boundless opportunities technology holds to create a brighter future."
